name: Deploy to Azure App Service(Windy)

on:
  push:
    branches: 
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        
      - name: Setup the Node.js version
        uses: actions/setup-node@v4
        with: 
          node-version: '18.x'

      - name: Install dependicies
        run: npm install

      - name: Deploy to Azure App Services
        uses: azure/webapps-deploy@v2
        with:
          app-name: WindyTestApp
          publish-profile: ${{ secrets.WINDY_AZURE_INITIAL }}
          package: .